main_background_color = 'grey21'
main_font_color = 'white'
button_font_color = 'white'
button_color = '#0066b2'
frame_background_color = 'grey22'
preview_backgorund_color = 'grey32'
hazardous_asteroid_color = '#ec1c24'
